DOCS-248: add details
inrupt/docs-pod-browser pull request #9
Opened 2021-01-28 21:02 UTC by kay-kim

Not too comprehensive - as ultimately, as the user-interface itself should strive to be intuitive.

2021-01-28 21:11 UTC, kay-kim commented on source/index.rst
https://docs-inrupt-private-git-stage-podbrowser.kay-kim.vercel.app/

2021-01-28 21:11 UTC, kay-kim commented on source/login.rst
> +=======================
https://docs-inrupt-private-git-stage-podbrowser.kay-kim.vercel.app/login/

2021-01-28 21:11 UTC, kay-kim commented on source/manage-bookmarks.rst
> +====================================
https://docs-inrupt-private-git-stage-podbrowser.kay-kim.vercel.app/manage-bookmarks/

2021-01-28 21:11 UTC, kay-kim commented on source/manage-contacts.rst
> +==============================
https://docs-inrupt-private-git-stage-podbrowser.kay-kim.vercel.app/manage-contacts/

2021-01-28 21:11 UTC, kay-kim commented on source/manage-files.rst
> +=======================
https://docs-inrupt-private-git-stage-podbrowser.kay-kim.vercel.app/manage-files/

2021-01-28 21:11 UTC, kay-kim commented on source/update-profile.rst
> +==============
https://docs-inrupt-private-git-stage-podbrowser.kay-kim.vercel.app/update-profile/

2021-02-01 13:36 UTC, kevin-inrupt requested changes
Looked good. As an FYI, Kyra is proposing changes to the designs :-(

2021-02-01 13:36 UTC, brownhoward commented on source/manage-files.rst
> +To view the details of a folder,
Formatting seems off here. Should it be a numbered list like other pages?

2021-02-01 13:36 UTC, brownhoward commented on source/manage-files.rst
> +To view the details of a file/Resource,
As above, formatting seems off.

2021-02-01 13:36 UTC, kevin-inrupt commented on source/manage-contacts.rst
> +To manage contacts in PodBrowser, switch to the :guilabel:`Contacts`
Seems repetitive.  Maybe "To manage contacts in PodBrowser, switch to the :guilabel:`Contacts` view by clicking on the Contacts icon on the top menu bar."

2021-02-01 13:36 UTC, kevin-inrupt commented on source/manage-files.rst
> +
If you want bookmark the folder you are currently viewing:

#. Click the Pod Indicator dropdown just below the Account menu.

#.  Select the :guilabel:`Bookmark Pod` option

2021-02-01 13:36 UTC, kevin-inrupt commented on source/manage-files.rst
> +
If you want to navigate directly to a Container in your Pod, or even in another Pod:

#. Click the Pod Indicator dropdown just below the Account menu.

#. Select the :guilabel:`Change Pod` option.

#. Enter the full URL of the Container to which you want to navigate (e.g., `https://<Pod URL/public`).

#. Click :guilabel:`GO`

The contents of the Container will be displayed if you have Read access.

2021-02-01 15:45 UTC, kay-kim commented on source/manage-files.rst
> +To view the details of a folder,
Updated.

2021-02-01 15:47 UTC, kay-kim commented on source/manage-files.rst
> +To view the details of a file/Resource,
updated

2021-02-01 15:50 UTC, kay-kim commented
Yeah - I figured we'd change the designs of these quite a bit in the early days.  That's okay - I expected frequent updates in the beginning (hence, this isn't particularly in-depth).  Probably in 9 mos or so, we can remove the images; and although the designs might change, at least, by that time, the labels and UI organization will be more stable so that the steps will remain somewhat stable.

2021-02-01 19:28 UTC, kevin-inrupt approved these changes

2021-02-01 19:40 UTC, merged